### PR TITLE
dll & fuse: Added "AddWriteEaPerm" mount option.

### LINKED ISSUE #604: Files with mode 0666 cannot be overwritten by "Everyone" user
Our team implemented a [filesystem](https://github.com/juicedata/juicefs) on Windows using the WinFsp FUSE layer. I found that when a file’s mode is set to 0666, it cannot be overwritten as an “others” user on Windows—attempting to overwrite yields “Permission denied,” as shown below:

Image

Using FileSpy to trace the relevant IRP requests, I saw that for FILE_OVERWRITE_IF the requested DesiredAccess is 0x120196, which includes these permissions:
```
	•	FILE_ADD_FILE             0x00000002
	•	FILE_WRITE_DATA           0x00000002
	•	FILE_ADD_SUBDIRECTORY     0x00000004
	•	FILE_APPEND_DATA          0x00000004
	•	FILE_WRITE_EA             0x00000010
	•	FILE_READ_ATTRIBUTES      0x00000080
	•	FILE_WRITE_ATTRIBUTES     0x00000100
	•	READ_CONTROL              0x00020000
	•	SYNCHRONIZE               0x00100000
```

However, when WinFsp converts the FUSE mode 6 (owner-group-others bits) into Windows access masks, I noticed that FILE_WRITE_EA is missing. As a result, the subsequent AccessCheck call fails. The relevant code snippet is shown below:

```
    if (!AddAccessAllowedAce(Acl, ACL_REVISION,
        FspPosixDefaultPerm | FspPosixMapPermissionToAccessMask(Mode, WorldPerm),
        FspWorldSid))
        goto lasterror;

#define FspPosixDefaultPerm             \
    (SYNCHRONIZE | READ_CONTROL | FILE_READ_ATTRIBUTES | FILE_READ_EA)

#define FspPosixOwnerDefaultPerm        \
    (FspPosixDefaultPerm | DELETE | WRITE_DAC | WRITE_OWNER | FILE_WRITE_ATTRIBUTES | FILE_WRITE_EA)

static inline ACCESS_MASK FspPosixMapPermissionToAccessMask(UINT32 Mode, UINT32 Perm)
{
    ACCESS_MASK DeleteChild = 0040000 == (Mode & 0041000) ? FILE_DELETE_CHILD : 0;

    return
        ((Perm & 4) ? FILE_READ_DATA : 0) |
        ((Perm & 2) ? FILE_WRITE_ATTRIBUTES | FILE_WRITE_DATA | FILE_APPEND_DATA | DeleteChild : 0) |
        ((Perm & 1) ? FILE_EXECUTE : 0);
}

```

The previous code shows that only the file owner has the "FILE_WRITE_EA" permission. I tried to modify the FspPosixMapPermissionToAccessMask code to assign the FILE_WRITE_EA when the mode contains the "w" permission, and it works fine in this case.

### My questions are:

1. Why doesn’t WinFsp grant FILE_WRITE_EA to the “world” user when the mode is 0666? Or is this intentional?
2. If it is intentional, is there any current workaround to allow the “Everyone” SID to overwrite files when mode is 0666? (I read the FSD code and DLL code, but I couldn't find a method to do that, disabling the EA support doesn't seem to work)
3. Since my filesystem doesn’t actually support EA(I confirm this by tracking the "fsp_fuse_loop_start" code), should winfsp filter out EA-related bits from the requested DesiredAccess before calling the CheckAccess?

Thank you for taking the time to look into this issue.

### PR DESCRIPTION
**Pull request by chenjie4255**
## Description 

Following the discussion in PR #610, this PR attempts to add a per-mount ```AddWriteEaPerm``` FUSE option. When enabled, it modifies the security descriptor to add FILE_WRITE_EA permission to ACEs that already have FILE_WRITE_DATA, no matter the ACE type is allow or deny.

## Testing
I've done some basic testing with the option enabled and disabled, and it appears to address the issue described in #604 while maintaining backward compatibility. However, more thorough testing and review would be appreciated.

---

Fixes #604
Supersedes #610

Thanks for reviewing. Please let me know if I've misunderstood anything or if there are improvements to be made.

----

Before submitting this PR please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Contributing**: You MUST read and be willing to accept the [CONTRIBUTOR AGREEMENT](https://github.com/winfsp/winfsp/blob/master/Contributors.asciidoc). The agreement gives joint copyright interests in your contributions to you and the original WinFsp author. If you have already accepted the [CONTRIBUTOR AGREEMENT](https://github.com/winfsp/winfsp/blob/master/Contributors.asciidoc) you do not need to do so again.
- [x] **Topic branch**: Avoid creating the PR off the master branch of your fork. Consider creating a topic branch and request a pull from that. This allows you to add commits to the master branch of your fork without affecting this PR.
- [x] **No tabs**: Consistently use SPACES everywhere. NO TABS, unless the file format requires it (e.g. Makefile).
- [x] **Style**: Follow the same code style as the rest of the project.
- [ ] **Tests**: Include tests to the extent that it is possible, especially if you add a new feature.
- [x] **Quality**: Your design and code should be of high quality and something that you are proud of.

### CODE REVIEW

File: src/dll/fuse/fuse_intf.c [hunk 1]
```diff
@@ -545,6 +545,44 @@ static NTSTATUS fsp_fuse_intf_GetFileInfoFunnel(FSP_FILE_SYSTEM *FileSystem,
...
+{
+    BOOL DaclPresent, DaclDefaulted;
+    PACL Dacl;
+    ACL_SIZE_INFORMATION AclSizeInfo;
+    PACE_HEADER Ace;
+    PACCESS_MASK AccessMask;
+
+    if (!GetSecurityDescriptorDacl(SecurityDescriptor, &DaclPresent, &Dacl, &DaclDefaulted))
+        return;
+    if (!DaclPresent || 0 == Dacl)
```
Comment (billziss-gh) [inline src/dll/fuse/fuse_intf.c]: I think that if `0 != Dacl` then `DaclPresent == TRUE` (but not the other way around). So it should be safe to simply check: `if (0 == Dacl)`.

Do you find otherwise?

**Comment by billziss-gh** [comment]
An additional comment: The name `AddWriteEaPerm` was based on the original `FspAddWriteEAPermToPosixWriteBit` name. However Windows calls these ["access rights"](https://learn.microsoft.com/en-us/windows/win32/fileio/file-access-rights-constants) and not "permissions".

So I think a better name would be `AddWriteEaAccess`. Related names would have to be changed accordingly.

**Comment by billziss-gh** [comment]
I am merging this in. Thank you for your contributions!
